name: sg-setup
on:
  push:
    paths:
      - 'dev/sg/dependencies/**.go'
      - 'dev/sg/internal/check/**.go'

jobs:
  test:
    strategy:
      matrix:
        # See https://github.com/actions/virtual-environments#available-environments for
        # available environments.
        os: [macos-11, ubuntu-20.04]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test dependencies (${{ matrix.os }})
        run: go test -v ./dev/sg/dependencies/... -sg-setup=${{ matrix.os }}
        continue-on-error: true

      # We run the test twice because certain sg setup tasks might require a restart, and
      # also because things will inevitably flaked.
      #
      # If everything already worked, this should be pretty fast, and a good test of
      # validating an existing system.
      - name: Test dependencies attempt 2 (${{ matrix.os }})
        run: go test -v ./dev/sg/dependencies/... -sg-setup=${{ matrix.os }}
