name: sg-setup
on:
  push:
    paths:
      - 'dev/sg/dependencies/**.go'
      - 'dev/sg/internal/check/**.go'
jobs:
  test:
    strategy:
      matrix:
        os: [macos-12, ubuntu-12]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test dependencies (${{ matrix.os }})
        run: go test -v ./dev/sg/dependencies/... -sg-setup=${{ matrix.os }}
